baseURL: https://karinabertolino.netlify.app/
languageCode: en-us
title: Karina Bertolino
theme: hugo-theme-cactus
copyright: "&copy; 2022 Karina Bertolino"
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: CV 
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: Artwork
      url: /about
      weight: 4
markup:
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: no
    noClasses: yes
    style: dracula
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: white
  comments:
    cactuscomments:
      siteName: your_cactus_comments_sitename
    enabled: yes
    engine: cactus_comments
    utterances:
      label: hugo-site-name
      repo: <github_username>/<github_reponame>
      theme: github-light
  dateFormat: '2006-01-02'
  description: Postdoctoral researcher at Department of Linguistics, University of São Paulo 
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: yes
  showAllPostsArchive: no
  showAllPostsOnHomePage: no
  showProjectsList: yes
  showReadTime: yes
  social:
    - link: https://github.com/kgb32
      name: github
    - link: karina.bertolino@usp.br
      name: email
  tagsOverview: yes
